"""Allow employee_id to be nullable

Revision ID: 60fad123d259
Revises: ed85a0b4327a
Create Date: 2024-08-21 01:39:32.033434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60fad123d259"
down_revision: Union[str, None] = "ed85a0b4327a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "employee_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "employee_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
